---
title: "Time Value of Money"
Subtitle: "Quantitative Methods"
format:
  html:
    self-contained: true
    css: styles.css
    toc: False
---

In general, the relationship between a current or present value ($PV$) and future
value ($FV$) of a cash flow, where $r$ is the stated discount rate per period and $t$ is the
number of compounding periods, is as follows:

$$FV_t = PV(1+r)^t \tag{1}$$

---

If the number of compounding periods t is very large, that is, $t \to \infty$, we compound
the initial cash flow on a continuous basis as follows:

$$FV_t = PVe^{r t} \tag{2}$$

---

Conversely, present values can be expressed in future value terms, which requires
recasting Equation 1 as follows:

$$FV_t = PV(1+r)^t$$
$$PV = FV_t \left[ \frac{1}{(1+r)^t} \right]$$
$$PV = FV_t (1+r)^{-t} \tag{3}$$

---

The continuous time equivalent expression of Equation 3 is as follows:

$$PV_t = FV e^{-rt} \tag{4}$$

---

The present value $(PV)$ calculation for a discount bond with principal $(FV)$ paid at
time $t$ with a market discount rate of $r$ per period is:

$$PV(Discount Bond) = FV_t / (1+r)^t \tag{5}$$

The investor’s sole source of return is the difference between the price paid (PV) and
full principal (FV) received at maturity. This type of bond is often referred to as a
zero-coupon bond given the lack of intermediate interest cash flows, which for bonds
are generally referred to as coupons.

---

Pricing a coupon bond extends the single cash flow calculation for a discount bond to
a general formula for calculating a bond’s price $(PV)$ given the market discount rate
on a coupon date, as follows:

PV(Coupon Bond)
$$= \frac{PMT_1}{(1+r)^1} + \frac{PMT_2}{(1+r)^2} + \dots + \frac{PMT_N + FV_N}{(1+r)^N} \tag{6}$$

--- 

A perpetual bond is a less common type of coupon bond with no stated maturity
date. Most perpetual bonds are issued by companies to obtain equity-like financing
and often include redemption features. As $N \to \infty$ in Equation 6, we can simplify this
to solve for the present value of a perpetuity (or perpetual fixed periodic cash flow
without early redemption), where $r > 0$, as follows:

$$PV_{\text{Perpetual Bond}} = \frac{PMT}{r} \tag{7}$$

---


We may calculate the periodic annuity cash flow $(A)$, which occurs at the end of each
respective period, as follows:

$$A = \frac{r(PV)}{1-(1+r)^{-t}} \tag{8}$$

where:

$A$ = periodic cash flow,

$r$ = market interest rate per period,

$PV$ = present value or principal amount of loan or bond, and

$t$ = number of payment periods.

---


The price of a preferred or common share expected to pay a constant periodic dividend
is an infinite series that simplifies to the formula for the present value of a perpetuity
shown and is similar to the valuation of a perpetual bond that we encountered earlier.
Specifically, the valuation in Equation 7:

$$
PV_t = \sum\nolimits_{i=1}^{\infty} \frac{D_t}{(1+r)^i} \text{, and} \tag{9}
$$

$$PV_t = \frac{D_t}{r} \tag{10}$$

---

If dividends grow at a rate of g per period and are paid at the end of each period, the
next dividend (at time $t+1$) may be shown as follows:

$$D_{t+1} = D_t(1+g) \tag{11}$$

or generally in $i$ periods as:

$$D_{t+i} = D_t(1+g)^i \tag{12}$$

If dividend cash flows continue to grow at $g$ indefinitely, then we may rewrite Equation 10
as follows:

$$PV_t = \sum\nolimits_{i=1}^{\infty} \frac{D_t(1+g)^i}{(1+r)^i} \tag{13}$$

which simplifies to:

$$PV_t = \frac{D_t(1+g)}{r-g} = \frac{D_{t+1}}{r-g} \tag{14}$$

where $r-g > 0$.

---


The example in Exhibit 6 shows a company with an initial higher short-term dividend
growth of $g_s$ for the first three years, followed by lower long-term growth $(g_l \text{, where }g_s > g_l)$ indefinitely thereafter. If we generalize the initial growth phase to $n$ periods
followed by indefinite slower growth at $g_l$, we obtain a modified version of Equation
14 as follows:

$$PV_t = \sum\nolimits_{i=1}^{n} \frac{D_t(1+g_s)^i}{(1+r)^i} + \sum\nolimits_{j=n+1}^{\infty} \frac{D_{t+n}(1+g_l)^j}{(1+r)^j} \tag{15}$$

Note that the second expression in Equation 15 involves constant growth starting in
$n$ periods, for which we can substitute the geometric series simplification:

$$PV_t = \sum\nolimits_{i=1}^{n} \frac{D_t(1+g_s)^i}{(1+r)^i} + \frac{E(S_{t+n})}{(1+r)^n} \tag{16}$$

where the stock value of the stock in n periods $(E(S_{t+n})$ is referred to as the terminal
value) and is equal to the following:

$$E(S_{t+n}) = \frac{D_{t+n+1}}{r-g_l} \tag{17}$$

---

We may rearrange Equation 5 from earlier to solve for the implied periodic return
earned over the life of the instrument ($t$ periods):

$$r = \sqrt[t]{\frac{FV_t}{PV}} - 1 = \left( \frac{FV_t}{PV} \right)^{\frac{1}{t}} - 1 \tag{18}$$

---

The $YTM$ assumes an investor expects to receive all promised cash flows through
maturity and reinvest any cash received at the same $YTM$. For coupon bonds, this
involves periodic interest payments only, while for level payment instruments such
as mortgages, the calculation assumes both interest and amortized principal may
be invested at the same rate. Like other internal rates of return, the $YTM$ cannot be
solved using an equation, but it may be calculated using iteration with a spreadsheet
or calculator, a process that solves for $r$ in Equation 19, as follows:

$$PV(Coupon\ Bond)
= \frac{PMT_1}{(1+r)^1} + \frac{PMT_2}{(1+r)^2} + \dots + \frac{PMT_N + FV_N}{(1+r)^N} \tag{19}$$

where $FV$ equals a bond’s principal and $N$ is the number of periods to maturity.

The Microsoft Excel or Google Sheets $YIELD$ function can be used to calculate
$YTM$ for fixed-income instruments with periodic interest and full principal payment
at maturity:

= YIELD (settlement, maturity, rate, pr, redemption, frequency, [basis])

where:

settlement = settlement date entered using the DATE function;

maturity = maturity date entered using the DATE function;

rate = semi-annual (or periodic) coupon;

pr = price per 100 face value;

redemption = future value at maturity;

frequency = number of coupons per year; and

[basis] = day count convention, 1 through 5 for US bonds (30/360 day count).

---

Equity Instruments, Implied Return, and Implied Growth

As noted in the discussion of calculating the present value of an equity investment,
the price of a share of stock reflects not only the required return but also the growth
of cash flows. If we begin with an assumption of constant growth of dividends from
Equation 14, we can rearrange the formula as follows:

$$r - g = \frac{D_t(1+g)}{PV_t} = \frac{D_{t+1}}{PV_t} \tag{20}$$

The left-hand side of Equation 20 simply reflects the difference between the required
return and the constant growth rate, and the right-hand side is the dividend yield of the
stock based on expected dividends over the next period. Thus, the implied return on a
stock given its expected dividend yield and growth is given by Equation 21, as follows:

$$r = \frac{D_t(1+g)}{PV_t} + g = \frac{D_{t+1}}{PV_t} + g \tag{21}$$

Simply put, if we assume that a stock’s dividend grows at a constant rate in perpetuity,
the stock’s implied return is equal to its expected dividend yield plus the constant
growth rate.

Alternatively, we may be interested in solving for a stock’s implied growth rate,
and this relation is given by Equation 22:

$$g = \frac{r * PV_t - D_t}{PV_t + D_t} = r - \frac{D_{t+1}}{PV_t} \tag{22}$$

---

Implied Return and Growth

Price-to-earnings ratios not only are used for individual stocks but also are a val-
uation metric for stock indexes, such S&P 500, FTSE 100, or Nikkei 225. Here, the
stock index value is divided by a weighted sum of the index constituents’ earnings
per share. This will be explored in depth later in the curriculum, but we can relate
the price-to-earnings ratio to our earlier discussion of relating a stock’s price ($PV$) to
expected future cash flows to make some useful observations. First, recall Equation 14:

$$PV_t = \frac{D_t(1+g)}{r-g}$$

We can divide both sides by $E_t$, earnings per share for period $t$, to obtain:

$$\frac{PV_t}{E_t} = \frac{ \frac{D_t}{E_t} \times (1+g) }{ r - g } \tag{23}$$

The left-hand side of Equation 23 is the price-to-earnings ratio, whereas the first term
in the numerator on the right is the proportion of earnings distributed to shareholders
as dividends known as the **dividend payout ratio**.

--- 

In practice, the **forward price-to-earnings ratio** or ratio of its share price to an
estimate of its next period (t+1) earnings per share is commonly used. With it, we
can simplify the previous equation as follows:

$$\frac{PV_t}{E_{t+1}} = \frac{ \frac{D_{t+1}}{E_{t+1}} }{ r - g }\tag{24}$$

From Equation 24, we can see that forward price-to-earnings ratio is positively related
to higher expected dividend payout ratio and higher expected growth but is negatively
related to the required return.

---

Under the cash flow additivity principle, a risk-neutral investor would be indifferent
between strategies 1 and 2 under the following condition:

$$FV_2 = PV_0 \times (1+r_2)^2 = PV_0 \times (1+r_1)(1+F_{1,1}) \tag{25}$$

---
